---
# file: ansible-role-llvm/tasks/source.yml

- name: Set llvm_install_dir
  set_fact:
    llvm_install_dir: "/usr/local"
  tags:
    - clang
    - rhscl

- name: LLVM | clean build dir
  when: clean_build_dir|bool
  file:
    state: absent
    path: "{{ llvm_build_dir }}"

- name: LLVM | get from git repository
  git:
    repo: "{{ llvm_repo_url }}"
    dest: "{{ llvm_build_dir }}"
    version: "{{ llvm_version }}"

- name: source devtoolset and cmake profiles
  when: collections_enabled|bool and ansible_os_family == 'RedHat'
  set_fact:
    cmake_env: "source /etc/profile.d/cmake.sh"
    llvm_env: "source /opt/rh/llvm-toolset-7.0/enable"
  tags:
    - cmake
    - make
    - make_install

- name: LLVM | run cmake
  shell: |
    {{ cmake_env| default('') }} && \
    {{ llvm_env | default('') }} && \
    cmake -G "Unix Makefiles"  \
    -DCMAKE_INSTALL_PREFIX={{ llvm_install_dir }} \
    -DLLVM_ENABLE_ASSERTIONS=No \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_TARGETS_TO_BUILD=X86 llvm
  args:
    chdir: "{{ llvm_build_dir }}"
  changed_when: true
  tags:
    - cmake

- name: LLVM | make
  become: true
  shell: "{{ llvm_env | default('') }} && make -j {{ ansible_processor_vcpus }}"
  args:
    chdir: "{{ llvm_build_dir }}"
  changed_when: true
  tags:
    - make

- name: LLVM | install
  become: true
  shell: "{{ llvm_env | default('') }} && \
    make install -j {{ ansible_processor_vcpus }} "
  args:
    chdir: "{{ llvm_build_dir }}"
  changed_when: true
  tags:
    - make_install

- name: LLVM | add path to /etc/ld.so.conf.d/
  become: true
  template:
    src: llvm.conf-template.j2
    dest: "/etc/ld.so.conf.d/llvm-{{ llvm_version }}.conf"
    mode: 0644

- name: LLVM | run ldconfig
  become: true
  command: ldconfig
  changed_when: true

- name: LLVM | clean build dir
  when: clean_source_dir|bool
  file:
    state: absent
    path: "{{ llvm_build_dir }}"
...
