---
# https://access.redhat.com/documentation/en-us/red_hat_developer_tools/2018.4/html-single/using_clang_and_llvm_toolset/index
- name: RHSCL | install centos software collections
  package:
    name: centos-release-scl-rh
    state: present
    update_cache: true
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  when: ansible_distribution == 'CentOS'
  tags:
    - clang
    - rhscl

- name: RHSCL | enable rhel software variant devtools
  command: "yum-config-manager --enable rhel-7-variant-devtools-rpms"
  when:
    - ansible_distribution_major_version|int == 7
  tags:
    - clang
    - rhscl
    - notest
