---
# file: ansible-role-llvm/tasks/main.yml

# - name: LLVM | Check if the LLVM version is already installed
#   command: cat /var/cache/anxs-llvm-version
#   register: current_llvm_version
#   ignore_errors: yes
# yamllint disable-line rule:line-length
#   changed_when: current_llvm_version.rc != 0 or current_llvm_version.stdout != "{{llvm_version}}"
# - include: source.yml
#   when: current_llvm_version.changed
# - name: LLVM | Persist current version
#   copy: dest=/var/cache/anxs-llvm-version content="{{llvm_version}}"

- name: Install RedHat Software Collections
  when:
    - collections_enabled|bool
    - llvm_toolset == 'llvm-toolset-7.0'
    - not llvm_compilation|bool
    - ansible_os_family == 'RedHat'
  include: 'install-rhscl.yml'
  tags:
    - clang
    - rhscl

- name: Install Springdale Software Collections
  when:
    - collections_enabled|bool
    - llvm_toolset == 'llvm-toolset-6.0'
    - not llvm_compilation|bool
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int == 7
  include: 'springdale.yml'
  tags:
    - clang
    - springdale

- name: Compile LLVM+CLang
  when: llvm_compilation|bool and ansible_os_family == 'RedHat'
  include: 'compile-llvm.yml'
  tags:
    - clang
    - compile

- name: LLVM | cleanup devtoolset profile
  file:
    path: "/etc/profile.d/devtoolset.sh"
    state: absent
  tags:
    - clang
    - rhscl
    - notest

- name: LLVM | add environment variables to /etc/profile.d/llvm.sh
  become: true
  template:
    src: llvm.sh-template.j2
    dest: "/etc/profile.d/llvm.sh"
    mode: 0644
  tags:
    - clang
    - rhscl
...
