---
- hosts: all
  vars_files:
    - ../../defaults/main.yml
  vars:
    development_groupinstall: false
    DTSVER: 7
    CLANG: 10
  roles:
    - role: base_clang
      vars:
        collections_enabled: true
        llvm_compilation: false
      tags: 'clang'
